# Generated by Django 5.2.13 on 2026-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor_image',
            field=models.ImageField(blank=True, null=True, upload_to='measurement/'),
        ),
    ]
